CREATE TABLE LEADER_TBL (
LEADER_NAME 	VARCHAR(20) PRIMARY KEY,
LEADER_PW 		VARCHAR(100) NOT NULL,
LEADER_TEAM		VARCHAR(20) NOT NULL,
LEADER_GRADE	VARCHAR(20) NOT NULL,
LEADER_CLASS	VARCHAR(20) NOT NULL,
LEADER_COIN		SMALLINT
);

CREATE TABLE MEMBER_TBL (
MEMBER_NAME 	VARCHAR(20) PRIMARY KEY,
MEMBER_PW 		VARCHAR(20) NOT NULL,
MEMBER_CLASS	VARCHAR(20) NOT NULL,
MEMBER_GACHI	SMALLINT NOT NULL
);

CREATE TABLE CLASS_TBL (
CLASS_NAME		VARCHAR(20) PRIMARY KEY NOT NULL,
CLASS_MAIN		VARCHAR(10) NOT NULL,
CLASS_SUB		VARCHAR(10) NOT NULL,
CLASS_LANG		VARCHAR(20) NOT NULL,
CLASS_PATH      VARCHAR(10) NOT NULL
);

CREATE TABLE AUCTIONEER_TBL (
AUCTIONEER_INDEX	INT AUTO_INCREMENT PRIMARY KEY,
AUCTIONEER_NAME		VARCHAR(20) NOT NULL,
AUCTIONEER_APPEAL	VARCHAR(1000),
AUCTIONEER_DATE		DATETIME DEFAULT CURRENT_TIMESTAMP,
AUCTIONEER_TIMER	INT NOT NULL,
AUCTIONEER_GACHI	SMALLINT NOT NULL
);

CREATE TABLE RESULT_TBL (
RESULT_INDEX	INT AUTO_INCREMENT PRIMARY KEY,
RESULT_LEADER	VARCHAR(20) NOT NULL,
RESULT_MEMBER	VARCHAR(20) NOT NULL,
RESULT_DATE		DATETIME DEFAULT CURRENT_TIMESTAMP,
RESULT_COIN		SMALLINT NOT NULL
);

CREATE TABLE TEAM_TBL (
TEAM_INDEX		INT AUTO_INCREMENT PRIMARY KEY,
TEAM_LEADER		VARCHAR(20) NOT NULL,
TEAM_MEMBER		VARCHAR(20) NOT NULL,
TEAM_NAME		VARCHAR(100) NOT NULL,
TEAM_CLASS		VARCHAR(20) NOT NULL
);

ALTER TABLE AUCTIONEER_TBL ADD FOREIGN KEY (AUCTIONEER_NAME) REFERENCES MEMBER_TBL(MEMBER_NAME) ON DELETE CASCADE;
ALTER TABLE RESULT_TBL ADD FOREIGN KEY (RESULT_LEADER) REFERENCES LEADER_TBL(LEADER_NAME) ON DELETE CASCADE;
ALTER TABLE RESULT_TBL ADD FOREIGN KEY (RESULT_MEMBER) REFERENCES MEMBER_TBL(MEMBER_NAME) ON DELETE CASCADE;
ALTER TABLE TEAM_TBL ADD FOREIGN KEY (TEAM_LEADER) REFERENCES LEADER_TBL(LEADER_NAME) ON DELETE CASCADE;
ALTER TABLE TEAM_TBL ADD FOREIGN KEY (TEAM_MEMBER) REFERENCES MEMBER_TBL(MEMBER_NAME) ON DELETE CASCADE;
ALTER TABLE TEAM_TBL ADD FOREIGN KEY (TEAM_CLASS) REFERENCES CLASS_TBL(CLASS_NAME) ON DELETE CASCADE;

INSERT INTO CLASS_TBL VALUES ('App 특화', '강성관', '박승현', 'Java, Python', 'App');
INSERT INTO CLASS_TBL VALUES ('JS 특화 A', '조영태', '임승환', 'JavaScript, Python', 'JSA');
INSERT INTO CLASS_TBL VALUES ('JS 특화 B', '김철기', '선영표', 'JavaScript, Python', 'JSB');
INSERT INTO CLASS_TBL VALUES ('Spring 특화 A', '황해도', '한수진', 'Java, Python', 'SprA');
INSERT INTO CLASS_TBL VALUES ('Spring 특화 B', '박병관', '김용현', 'Java, Python', 'SprB');
INSERT INTO CLASS_TBL VALUES ('사물지능', '나예호', '홍성채', 'Python', 'SAMUL');
INSERT INTO CLASS_TBL VALUES ('언어지능', '최석재', '임현수', 'Python', 'UNUH');
INSERT INTO CLASS_TBL VALUES ('시각지능', '박웅근', '김태현', 'Python', 'SIGAK');
INSERT INTO CLASS_TBL VALUES ('클라우드 A', '손정현', '조자연', 'Python', 'CLDA');
INSERT INTO CLASS_TBL VALUES ('클라우드 B', '박태우', '정정용', 'Python', 'CLDB');

SELECT * FROM LEADER_TBL;
SELECT * FROM MEMBER_TBL;
SELECT * FROM CLASS_TBL;
SELECT * FROM AUCTIONEER_TBL;
SELECT * FROM RESULT_TBL;
SELECT * FROM TEAM_TBL;

-- 정보 확인용 회원 정보 INSERT 구문 ----------------------------

INSERT INTO MEMBER_TBL VALUES ("A1", "A1", "App", 10);
INSERT INTO MEMBER_TBL VALUES ("B1", "B1", "App", 20);
INSERT INTO MEMBER_TBL VALUES ("C1", "C1", "App", 30);
INSERT INTO MEMBER_TBL VALUES ("D1", "D1", "App", 40);
INSERT INTO MEMBER_TBL VALUES ("E1", "E1", "App", 50);

INSERT INTO MEMBER_TBL VALUES ("A2", "A2", "JSA", 60);
INSERT INTO MEMBER_TBL VALUES ("B2", "B2", "JSA", 70);
INSERT INTO MEMBER_TBL VALUES ("C2", "C2", "JSA", 80);
INSERT INTO MEMBER_TBL VALUES ("D2", "D2", "JSA", 90);
INSERT INTO MEMBER_TBL VALUES ("E2", "E2", "JSA", 100);

INSERT INTO MEMBER_TBL VALUES ("A3", "A3", "JSB", 10);
INSERT INTO MEMBER_TBL VALUES ("B3", "B3", "JSB", 20);
INSERT INTO MEMBER_TBL VALUES ("C3", "C3", "JSB", 30);
INSERT INTO MEMBER_TBL VALUES ("D3", "D3", "JSB", 40);
INSERT INTO MEMBER_TBL VALUES ("E3", "E3", "JSB", 50);

INSERT INTO MEMBER_TBL VALUES ("A4", "A4", "SprA", 60);
INSERT INTO MEMBER_TBL VALUES ("B4", "B4", "SprA", 70);
INSERT INTO MEMBER_TBL VALUES ("C4", "C4", "SprA", 80);
INSERT INTO MEMBER_TBL VALUES ("D4", "D4", "SprA", 90);
INSERT INTO MEMBER_TBL VALUES ("E4", "E4", "SprA", 100);

INSERT INTO MEMBER_TBL VALUES ("A5", "A5", "SprB", 10);
INSERT INTO MEMBER_TBL VALUES ("B5", "B5", "SprB", 20);
INSERT INTO MEMBER_TBL VALUES ("C5", "C5", "SprB", 30);
INSERT INTO MEMBER_TBL VALUES ("D5", "D5", "SprB", 40);
INSERT INTO MEMBER_TBL VALUES ("E5", "E5", "SprB", 50);

INSERT INTO MEMBER_TBL VALUES ("A6", "A6", "SAMUL", 60);
INSERT INTO MEMBER_TBL VALUES ("B6", "B6", "SAMUL", 70);
INSERT INTO MEMBER_TBL VALUES ("C6", "C6", "SAMUL", 80);
INSERT INTO MEMBER_TBL VALUES ("D6", "D6", "SAMUL", 90);
INSERT INTO MEMBER_TBL VALUES ("E6", "E6", "SAMUL", 100);

INSERT INTO MEMBER_TBL VALUES ("A7", "A7", "SIGAK", 10);
INSERT INTO MEMBER_TBL VALUES ("B7", "B7", "SIGAK", 20);
INSERT INTO MEMBER_TBL VALUES ("C7", "C7", "SIGAK", 30);
INSERT INTO MEMBER_TBL VALUES ("D7", "D7", "SIGAK", 40);
INSERT INTO MEMBER_TBL VALUES ("E7", "E7", "SIGAK", 50);

INSERT INTO MEMBER_TBL VALUES ("A8", "A8", "UNUH", 60);
INSERT INTO MEMBER_TBL VALUES ("B8", "B8", "UNUH", 70);
INSERT INTO MEMBER_TBL VALUES ("C8", "C8", "UNUH", 80);
INSERT INTO MEMBER_TBL VALUES ("D8", "D8", "UNUH", 90);
INSERT INTO MEMBER_TBL VALUES ("E8", "E8", "UNUH", 100);

INSERT INTO MEMBER_TBL VALUES ("A9", "A9", "CLDA", 10);
INSERT INTO MEMBER_TBL VALUES ("B9", "B9", "CLDA", 20);
INSERT INTO MEMBER_TBL VALUES ("C9", "C9", "CLDA", 30);
INSERT INTO MEMBER_TBL VALUES ("D9", "D9", "CLDA", 40);
INSERT INTO MEMBER_TBL VALUES ("E9", "E9", "CLDA", 50);

INSERT INTO MEMBER_TBL VALUES ("A10", "A10", "CLDB", 60);
INSERT INTO MEMBER_TBL VALUES ("B10", "B10", "CLDB", 70);
INSERT INTO MEMBER_TBL VALUES ("C10", "C10", "CLDB", 80);
INSERT INTO MEMBER_TBL VALUES ("D10", "D10", "CLDB", 90);
INSERT INTO MEMBER_TBL VALUES ("E10", "E10", "CLDB", 100);

-- 정보 확인용 회원 정보 INSERT 구문 ----------------------------

INSERT INTO LEADER_TBL VALUES ("A1", "A1", "A1", "A", "App", 10);
INSERT INTO LEADER_TBL VALUES ("B1", "B1", "A1", "A", "App", 20);
INSERT INTO LEADER_TBL VALUES ("C1", "C1", "A1", "A", "App", 30);
INSERT INTO LEADER_TBL VALUES ("D1", "D1", "A1", "A", "App", 40);
INSERT INTO LEADER_TBL VALUES ("E1", "E1", "A1", "A", "App", 50);

INSERT INTO LEADER_TBL VALUES ("A2", "A2", "A2", "A", "JSA", 60);
INSERT INTO LEADER_TBL VALUES ("B2", "B2", "A2", "A", "JSA", 70);
INSERT INTO LEADER_TBL VALUES ("C2", "C2", "A2", "A", "JSA", 80);
INSERT INTO LEADER_TBL VALUES ("D2", "D2", "A2", "A", "JSA", 90);
INSERT INTO LEADER_TBL VALUES ("E2", "E2", "A2", "A", "JSA", 100);

INSERT INTO LEADER_TBL VALUES ("A3", "A3", "A3", "A", "JSB", 10);
INSERT INTO LEADER_TBL VALUES ("B3", "B3", "A3", "A", "JSB", 20);
INSERT INTO LEADER_TBL VALUES ("C3", "C3", "A3", "A", "JSB", 30);
INSERT INTO LEADER_TBL VALUES ("D3", "D3", "A3", "A", "JSB", 40);
INSERT INTO LEADER_TBL VALUES ("E3", "E3", "A3", "A", "JSB", 50);

INSERT INTO LEADER_TBL VALUES ("A4", "A4", "A4", "A", "SprA", 60);
INSERT INTO LEADER_TBL VALUES ("B4", "B4", "A4", "A", "SprA", 70);
INSERT INTO LEADER_TBL VALUES ("C4", "C4", "A4", "A", "SprA", 80);
INSERT INTO LEADER_TBL VALUES ("D4", "D4", "A4", "A", "SprA", 90);
INSERT INTO LEADER_TBL VALUES ("E4", "E4", "A4", "A", "SprA", 100);

INSERT INTO LEADER_TBL VALUES ("A5", "A5", "A5", "A", "SprB", 10);
INSERT INTO LEADER_TBL VALUES ("B5", "B5", "A5", "A", "SprB", 20);
INSERT INTO LEADER_TBL VALUES ("C5", "C5", "A5", "A", "SprB", 30);
INSERT INTO LEADER_TBL VALUES ("D5", "D5", "A5", "A", "SprB", 40);
INSERT INTO LEADER_TBL VALUES ("E5", "E5", "A5", "A", "SprB", 50);

INSERT INTO LEADER_TBL VALUES ("A6", "A6", "A6", "A", "SAMUL", 60);
INSERT INTO LEADER_TBL VALUES ("B6", "B6", "A6", "A", "SAMUL", 70);
INSERT INTO LEADER_TBL VALUES ("C6", "C6", "A6", "A", "SAMUL", 80);
INSERT INTO LEADER_TBL VALUES ("D6", "D6", "A6", "A", "SAMUL", 90);
INSERT INTO LEADER_TBL VALUES ("E6", "E6", "A6", "A", "SAMUL", 100);

INSERT INTO LEADER_TBL VALUES ("A7", "A7", "A7", "A", "SIGAK", 10);
INSERT INTO LEADER_TBL VALUES ("B7", "B7", "A7", "A", "SIGAK", 20);
INSERT INTO LEADER_TBL VALUES ("C7", "C7", "A7", "A", "SIGAK", 30);
INSERT INTO LEADER_TBL VALUES ("D7", "D7", "A7", "A", "SIGAK", 40);
INSERT INTO LEADER_TBL VALUES ("E7", "E7", "A7", "A", "SIGAK", 50);

INSERT INTO LEADER_TBL VALUES ("A8", "A8", "A8", "A", "UNUH", 60);
INSERT INTO LEADER_TBL VALUES ("B8", "B8", "A8", "A", "UNUH", 70);
INSERT INTO LEADER_TBL VALUES ("C8", "C8", "A8", "A", "UNUH", 80);
INSERT INTO LEADER_TBL VALUES ("D8", "D8", "A8", "A", "UNUH", 90);
INSERT INTO LEADER_TBL VALUES ("E8", "E8", "A8", "A", "UNUH", 100);

INSERT INTO LEADER_TBL VALUES ("A9", "A9", "A9", "A", "CLDA", 10);
INSERT INTO LEADER_TBL VALUES ("B9", "B9", "A9", "A", "CLDA", 20);
INSERT INTO LEADER_TBL VALUES ("C9", "C9", "A9", "A", "CLDA", 30);
INSERT INTO LEADER_TBL VALUES ("D9", "D9", "A9", "A", "CLDA", 40);
INSERT INTO LEADER_TBL VALUES ("E9", "E9", "A9", "A", "CLDA", 50);

INSERT INTO LEADER_TBL VALUES ("A10", "A10", "A10", "A", "CLDB", 60);
INSERT INTO LEADER_TBL VALUES ("B10", "B10", "A10", "A", "CLDB", 70);
INSERT INTO LEADER_TBL VALUES ("C10", "C10", "A10", "A", "CLDB", 80);
INSERT INTO LEADER_TBL VALUES ("D10", "D10", "A10", "A", "CLDB", 90);
INSERT INTO LEADER_TBL VALUES ("E10", "E10", "A10", "A", "CLDB", 100);