CREATE TABLE LEADER_TBL (
LEADER_NAME 	VARCHAR(20) PRIMARY KEY,
LEADER_PW 		VARCHAR(100) NOT NULL,
LEADER_TEAM		VARCHAR(20) NOT NULL,
LEADER_GRADE	VARCHAR(20) NOT NULL,
LEADER_CLASS	VARCHAR(20) NOT NULL,
LEADER_COIN		SMALLINT DEFAULT 10 NOT NULL
);

CREATE TABLE MEMBER_TBL (
MEMBER_NAME 	VARCHAR(20) PRIMARY KEY,
MEMBER_PW 		VARCHAR(20) NOT NULL,
MEMBER_CLASS	VARCHAR(20) NOT NULL,
MEMBER_GACHI	SMALLINT NOT NULL
);

CREATE TABLE CLASS_TBL (
CLASS_NAME		VARCHAR(20) PRIMARY KEY NOT NULL,
CLASS_MAIN		VARCHAR(10) NOT NULL,
CLASS_SUB		VARCHAR(10) NOT NULL,
CLASS_LANG		VARCHAR(20) NOT NULL,
CLASS_PATH      VARCHAR(10) NOT NULL
);

CREATE TABLE AUCTIONEER_TBL (
AUCTIONEER_INDEX	INT AUTO_INCREMENT PRIMARY KEY,
AUCTIONEER_NAME		VARCHAR(20) NOT NULL,
AUCTIONEER_APPEAL	VARCHAR(1000),
AUCTIONEER_DATE		DATETIME DEFAULT CURRENT_TIMESTAMP,
AUCTIONEER_TIMER	INT NOT NULL,
AUCTIONEER_GACHI	SMALLINT NOT NULL
);

CREATE TABLE RESULT_TBL (
RESULT_INDEX	INT AUTO_INCREMENT PRIMARY KEY,
RESULT_LEADER	VARCHAR(20) NOT NULL,
RESULT_MEMBER	VARCHAR(20) NOT NULL,
RESULT_DATE		DATETIME DEFAULT CURRENT_TIMESTAMP,
RESULT_COIN		SMALLINT NOT NULL
);

CREATE TABLE TEAM_TBL (
TEAM_INDEX		INT AUTO_INCREMENT PRIMARY KEY,
TEAM_LEADER		VARCHAR(20) NOT NULL,
TEAM_MEMBER		VARCHAR(20) NOT NULL,
TEAM_NAME		VARCHAR(100) NOT NULL
);

ALTER TABLE LEADER_TBL ADD FOREIGN KEY (LEADER_CLASS) REFERENCES CLASS_TBL(CLASS_NAME) ON DELETE CASCADE;
ALTER TABLE MEMBER_TBL ADD FOREIGN KEY (AUCTIONEER_NAME) REFERENCES MEMBER_TBL(MEMBER_NAME) ON DELETE CASCADE;
ALTER TABLE AUCTIONEER_TBL ADD FOREIGN KEY (AUCTIONEER_NAME) REFERENCES MEMBER_TBL(MEMBER_NAME) ON DELETE CASCADE;
ALTER TABLE RESULT_TBL ADD FOREIGN KEY (RESULT_LEADER) REFERENCES LEADER_TBL(LEADER_NAME) ON DELETE CASCADE;
ALTER TABLE RESULT_TBL ADD FOREIGN KEY (RESULT_MEMBER) REFERENCES MEMBER_TBL(MEMBER_NAME) ON DELETE CASCADE;
ALTER TABLE TEAM_TBL ADD FOREIGN KEY (TEAM_LEADER) REFERENCES LEADER_TBL(LEADER_NAME) ON DELETE CASCADE;
ALTER TABLE TEAM_TBL ADD FOREIGN KEY (TEAM_MEMBER) REFERENCES MEMBER_TBL(MEMBER_NAME) ON DELETE CASCADE;

INSERT INTO CLASS_TBL VALUES ('App 특화', '강성관', '박승현', 'Java, Python');
INSERT INTO CLASS_TBL VALUES ('JS 특화 A', '조영태', '임승환', 'JavaScript, Python');
INSERT INTO CLASS_TBL VALUES ('JS 특화 B', '김철기', '선영표', 'JavaScript, Python');
INSERT INTO CLASS_TBL VALUES ('Spring 특화 A', '황해도', '한수진', 'Java, Python');
INSERT INTO CLASS_TBL VALUES ('Spring 특화 B', '박병관', '김용현', 'Java, Python');
INSERT INTO CLASS_TBL VALUES ('사물지능', '나예호', '홍성채', 'Python');
INSERT INTO CLASS_TBL VALUES ('언어지능', '최석재', '임현수', 'Python');
INSERT INTO CLASS_TBL VALUES ('시각지능', '박웅근', '김태현', 'Python');
INSERT INTO CLASS_TBL VALUES ('클라우드 A', '손정현', '조자연', 'Python');
INSERT INTO CLASS_TBL VALUES ('클라우드 B', '박태우', '정정용', 'Python');

-- UPDATE 구문 실행 바람 ----------------------------
UPDATE CLASS_TBL SET CLASS_MAIN = '최석재' WHERE CLASS_NAME = '언어지능';
UPDATE CLASS_TBL SET CLASS_MAIN = '박웅근' WHERE CLASS_NAME = '시각지능';
UPDATE CLASS_TBL SET CLASS_MAIN = '손정현' WHERE CLASS_NAME = '클라우드 A';
UPDATE CLASS_TBL SET CLASS_MAIN = '박태우' WHERE CLASS_NAME = '클라우드 B';

-- CLASS_TBL ADD 구문 실행 바람 ----------------------------
ALTER TABLE CLASS_TBL ADD CLASS_PATH VARCHAR(10) AFTER CLASS_LANG;

-- CLASS_TBL UPDATE 구문 실행 바람 ----------------------------
UPDATE CLASS_TBL SET CLASS_PATH = 'App' WHERE CLASS_NAME = 'App 특화';
UPDATE CLASS_TBL SET CLASS_PATH = 'JSA' WHERE CLASS_NAME = 'JS 특화 A';
UPDATE CLASS_TBL SET CLASS_PATH = 'JSB' WHERE CLASS_NAME = 'JS 특화 B';
UPDATE CLASS_TBL SET CLASS_PATH = 'SprA' WHERE CLASS_NAME = 'Spring 특화 A';
UPDATE CLASS_TBL SET CLASS_PATH = 'SprB' WHERE CLASS_NAME = 'Spring 특화 B';
UPDATE CLASS_TBL SET CLASS_PATH = 'SAMUL' WHERE CLASS_NAME = '사물지능';
UPDATE CLASS_TBL SET CLASS_PATH = 'UNUH' WHERE CLASS_NAME = '언어지능';
UPDATE CLASS_TBL SET CLASS_PATH = 'SIGAK' WHERE CLASS_NAME = '시각지능';
UPDATE CLASS_TBL SET CLASS_PATH = 'CLDA' WHERE CLASS_NAME = '클라우드 A';
UPDATE CLASS_TBL SET CLASS_PATH = 'CLDB' WHERE CLASS_NAME = '클라우드 B';

-- ADD 구문 실행 바람 ----------------------------
ALTER TABLE CLASS_TBL ADD CLASS_PATH VARCHAR(10) AFTER CLASS_LANG;

SELECT * FROM LEADER_TBL;
SELECT * FROM MEMBER_TBL;
SELECT * FROM CLASS_TBL;
SELECT * FROM AUCTIONEER_TBL;
SELECT * FROM RESULT_TBL;
SELECT * FROM TEAM_TBL;